// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Lnv2uTdPbCBXbDpGBWjJQy9oh2hQMiU',
    appId: '1:736402354749:web:ac3fb538ca6f38735a7054',
    messagingSenderId: '736402354749',
    projectId: 'tentapp-951ed',
    authDomain: 'tentapp-951ed.firebaseapp.com',
    storageBucket: 'tentapp-951ed.firebasestorage.app',
    measurementId: 'G-C0JDEQ3FNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7GihbaBHGTpldR6-z-kQd-hqzutUXwOc',
    appId: '1:736402354749:android:e5dd69a35cbdfb415a7054',
    messagingSenderId: '736402354749',
    projectId: 'tentapp-951ed',
    storageBucket: 'tentapp-951ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUrUhCt9SXiLRy7-wNNLUjeN5MzOh9Yw',
    appId: '1:736402354749:ios:7ef1e6ce69af7ad95a7054',
    messagingSenderId: '736402354749',
    projectId: 'tentapp-951ed',
    storageBucket: 'tentapp-951ed.firebasestorage.app',
    iosBundleId: 'com.example.tentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtUrUhCt9SXiLRy7-wNNLUjeN5MzOh9Yw',
    appId: '1:736402354749:ios:7ef1e6ce69af7ad95a7054',
    messagingSenderId: '736402354749',
    projectId: 'tentapp-951ed',
    storageBucket: 'tentapp-951ed.firebasestorage.app',
    iosBundleId: 'com.example.tentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Lnv2uTdPbCBXbDpGBWjJQy9oh2hQMiU',
    appId: '1:736402354749:web:c76ca62f134f2f815a7054',
    messagingSenderId: '736402354749',
    projectId: 'tentapp-951ed',
    authDomain: 'tentapp-951ed.firebaseapp.com',
    storageBucket: 'tentapp-951ed.firebasestorage.app',
    measurementId: 'G-P3V4TT7MB5',
  );
}
